dist: xenial
group: travis_latest

if: |
  branch = master AND ! commit_message =~ /readme.md/ AND ! commit_message =~ /docker-compose.yml/
  OR type = cron

language: bash
sudo: required

services:
  - docker

env:

  global:
    - BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    - BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}"
    - DOCKER_DESCRIPTION="music downloader and organizer"
    - DOCKER_MAINTAINER="stlouisn"
    - DOCKER_NAME="lidarr"
    - DOCKER_URL="http://lidarr.audio/"
    - OS_NAME="ubuntu"
    - OS_CODENAME="$(curl -ksSL https://raw.githubusercontent.com/tianon/docker-brew-ubuntu-core/master/rolling)"
    - SCHEMA_VERSION="1.0"
    - VCS_REF="$(git rev-parse --short HEAD)"
    - VCS_URL="$(git remote get-url origin | head -c-5)"

  matrix:    
    - DOCKER_TAG="latest"
      DOCKER_VERSION="$(curl -sSL https://services.lidarr.audio/v1/update/develop/changes?os=linux | jq -r '.[0].version')"

before_install:
  - sudo /sbin/sysctl -w net.ipv4.conf.all.forwarding=1
  - sudo bash travis/docker.sh
  - sudo docker version

install:
  - sudo docker run --privileged linuxkit/binfmt:v0.7
  - sudo docker run --privileged -d -p 1234:1234 --name buildkit moby/buildkit:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/arm --oci-worker-platform linux/armhf --oci-worker-platform linux/arm64 --oci-worker-platform linux/amd64
  - sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
  - export BUILDKIT_HOST=tcp://0.0.0.0:1234

before_script:
  - sed -i -e '/^$/d' -e 's/^[ \t]*//' -e '/^#/d' dockerfiles/*
  - chmod 0544 rootfs/usr/local/bin/docker_entrypoint.sh
  - curl -ksSL -o lidarr.tar.gz "https://github.com/lidarr/Lidarr/releases/download/v${DOCKER_VERSION}/Lidarr.develop.${DOCKER_VERSION}.linux.tar.gz"
  - mkdir -p ./userfs
  - tar -xf lidarr.tar.gz -C userfs/

script:
  - sudo bash travis/build.sh
  - sudo bash travis/deploy.sh

after_success:

notifications:
  email:
    on_success: never
    on_failure: change
