language: bash
dist: trusty
sudo: required

branches:
  only:
    - master

env:
  global:
    - BUILD_DATE="`date -u +%Y-%m-%dT%H:%M:%SZ`"
    - BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}"
    - DOCKER_DESCRIPTION="download, sort, and rename television shows"
    - DOCKER_NAME="sonarr"
    - DOCKER_URL="https://sonarr.tv/"
    - DOCKER_VERSION="0.0"
    - MAINTAINER="stlouisn"
    - SCHEMA_VERSION="1.0"
    - VCS_REF="`git rev-parse --short HEAD`"
    - VCS_URL="`git remote get-url origin | head -c-5`"

before_install:
  - sudo apt-get update -q
  - sudo apt-get upgrade -q -y
  - docker version

install:
  - chmod 0744 rootfs/usr/local/bin/docker_entrypoint.sh

before_script:
  - sed -i -e '/^$/d' -e 's/^[ \t]*//' -e '/^#/d' Dockerfile

script:
  - >
    docker build
    --label org.label-schema.build-date="${BUILD_DATE}"
    --label org.label-schema.build-number="${BUILD_NUMBER}"
    --label org.label-schema.description="${DOCKER_DESCRIPTION}"
    --label org.label-schema.name="${DOCKER_NAME}"
    --label org.label-schema.url="${DOCKER_URL}"
    --label org.label-schema.version="${DOCKER_VERSION}"
    --label org.label-schema.maintainer="${MAINTAINER}"
    --label org.label-schema.schema-version="${SCHEMA_VERSION}"
    --label org.label-schema.vcs-ref="${VCS_REF}"
    --label org.label-schema.vcs-url="${VCS_URL}"
    --tag ${DOCKER_USERNAME}/${DOCKER_IMAGE}:latest
    --pull .

after_success:
  - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
  - docker push ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_RELEASE}
  - docker push ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_BRANCH}

notifications:
  email:
    on_success: never
    on_failure: change
