version: '2.3'

services:

  lidarr:
    image: stlouisn/lidarr:latest
    container_name: lidarr
    hostname: lidarr
    environment:
      - TZ=UTC
    restart: always
    volumes:
      - ./lidarr/config:/var/lib/lidarr:rw
      - ./storage/downloads:/downloads:rw
      - ./storage/music:/music:rw
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 8989
