version: '2.4'

services:

  lidarr:
    image: stlouisn/lidarr
    container_name: lidarr
    hostname: lidarr
    environment:
      - LC_ALL=C.UTF-8
      - TZ=UTC
    restart: always
    volumes:
      - /docker/lidarr/config:/config
      - /media/downloads:/downloads
      - /media/music:/music
    ports:
      - 4040:4040
